# =============================================================================
# MonWatch-UI Cyclone V3 — Satellite Imagery Analysis Workstation
# Meteorological Satellite Data Processing System for PWARDS-weather
# =============================================================================
#
# Organized and documented for open-source distribution and WMO compliance.
# Developed and field-tested since 2025 by PWARDS-weather.
# Operational since July 3, 2026.
#
# Module: core/products.py
# Description: RGB product definitions and spectral band configurations for satellite imagery compositing.
#
# Principal Developer: Zero (Prince Al Zhanjie B. Dela Rosa)
# Affiliation: PWARDS-weather
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# See also: https://www.apache.org/licenses/LICENSE-2.0
#
# Copyright (C) 2025-2026 PWARDS-weather (Pasacao Weather Atmospheric
# and Real-Time Data System)
#
# --- OPEN-SOURCE POLICY ---
# Redistribution or modification without formally notifying PWARDS-weather
# developers constitutes unauthorized use and violates the license terms.
# Developers must be notified via email or GitHub issue before any changes
# are distributed. See LICENSE file for complete terms.
# =============================================================================


RGB_PRODUCTS = {
    "natural": {
        "name": "Natural Color",
        "satellite": "himawari",
        "bands": ["B05", "B04", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B05", "min": 0.0, "max": 99.0, "gamma": 3.0},
            "G": {"band": "B04", "min": 0.0, "max": 100.0, "gamma": 2.95},
            "B": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "Snow/ice cyan, vegetation green, clouds white. (reflectance %)",
        "tag": "DAY",
    },
    "true": {
        "name": "True Color",
        "satellite": "himawari",
        "bands": ["B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "G": {"band": "B02", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "B": {"band": "B01", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "Rayleigh-corrected true color. (reflectance %)",
        "tag": "DAY",
    },
    "sandwich": {
        "name": "Sandwich",
        "satellite": "himawari",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "sandwich",
        "description": "VIS underlaid with IR; cold clouds red/orange. Auto day/night switching via SZA.",
        "tag": "ALL",
    },
    "true_daynight": {
        "name": "True Color Day/Night",
        "satellite": "himawari",
        "bands": ["B13", "B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "special": "true_daynight",
        "description": "True Color by day, IR night background with cold cloud overlay. Auto day/night switching via SZA.",
        "tag": "ALL",
    },
    "airmass": {
        "name": "Air Mass",
        "satellite": "himawari",
        "bands": ["B08", "B10", "B12", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B10", "min": -25.8, "max": 0, "gamma": 1.0},
            "G": {"band1": "B12", "band2": "B13", "min": -41.5, "max": 4.3, "gamma": 1.0},
            "B": {"band": "B08", "min": 208.0, "max": 242.6, "gamma": 1.0, "invert": True},
        },
        "description": "Jet streams, tropopause folds, WV.",
        "tag": "ALL",
    },
    "dust": {
        "name": "Dust RGB",
        "satellite": "himawari",
        "bands": ["B15", "B13", "B14", "B11"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3, "gamma": 1.0},
            "G": {"band1": "B14", "band2": "B11", "min": -0.5, "max": 15.0, "gamma": 2.2},
            "B": {"band": "B13", "min": 261.5, "max": 289.2, "gamma": 1.0},
        },
        "description": "Dust magenta/pink; thin cirrus dark; thick clouds brown.",
        "tag": "ALL",
    },
    "day_convection": {
        "name": "Day Convection",
        "satellite": "himawari",
        "bands": ["B05", "B03", "B07", "B08", "B10", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B10", "min": -35.0, "max": 5.0, "gamma": 1.0},
            "G": {"band1": "B07", "band2": "B13", "min": -5.0, "max": 60.0, "gamma": 0.5},
            "B": {"band1": "B03", "band2": "B05", "min": -10.0, "max": 70.0, "gamma": 0.95, "invert": True},
        },
        "description": "Intense convection yellow; small ice crystals bright.",
        "tag": "DAY",
    },
    "fire": {
        "name": "Fire Temp",
        "satellite": "himawari",
        "bands": ["B07", "B06", "B05"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B07", "min": 273.0, "max": 350.0, "gamma": 1.0},
            "G": {"band": "B06", "min": 0.0, "max": 50.0, "gamma": 1.0},
            "B": {"band": "B05", "min": 0.0, "max": 50.0, "gamma": 1.0},
        },
        "description": "Hot spots red/yellow; burn scars dark.",
        "tag": "DAY",
    },
    "night_microphysics": {
        "name": "Night Microphys.",
        "satellite": "himawari",
        "bands": ["B10", "B13", "B15", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3, "gamma": 1},
            "G": {"band1": "B03", "band2": "B10", "min": -2.9, "max": 7, "gamma": 1},
            "B": {"band": "B13", "min": 243.7, "max": 293.2, "gamma": 1},
        },
        "description": "Fog/low clouds aqua; high ice clouds red/purple.",
        "tag": "NIGHT",
    },
    "cloud_phase": {
        "name": "Cloud Phase",
        "satellite": "himawari",
        "bands": ["B05", "B06", "B02"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B05", "min": 1, "max": 50, "gamma": 1.0},
            "G": {"band": "B06", "min": 1, "max": 86, "gamma": 1.0},
            "B": {"band": "B02", "min": 0, "max": 86, "gamma": 1.0},
        },
        "description": "Ice clouds blue/cyan; liquid water white/green. (reflectance %)",
        "tag": "DAY",
    },
    "infrared": {
        "name": "Infrared",
        "satellite": "himawari",
        "bands": ["B13"],
        "single_band": True,
        "formula": {"band": "B13", "min": None, "max": None, "gamma": 0.5, "invert": True},
        "description": "Cold clouds white; warm ground black.",
        "tag": "ALL",
    },
    "day_microphysics": {
        "name": "Day Microphys.",
        "satellite": "himawari",
        "bands": ["B07", "B04", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B04", "min": 0, "max": 121.4829, "gamma": 0.95},
            "G": {"band": "B07", "min": 196.5965, "max": 352.6322, "gamma": 1},
            "B": {"band": "B13", "min": 203.5, "max": 303.2, "gamma": 1.0},
        },
        "description": "Ice vs water cloud discrimination.",
        "tag": "DAY",
    },
    "volcanic_ash": {
        "name": "Ash RGB",
        "satellite": "himawari",
        "bands": ["B11", "B13", "B14", "B15"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3.0, "gamma": 1.0},
            "G": {"band1": "B14", "band2": "B11", "min": -5.9, "max": 5.1, "gamma": 0.5},
            "B": {"band": "B13", "min": 243.6, "max": 303.2, "gamma": 1.0},
        },
        "description": "Ash cloud detection and tracking.",
        "tag": "ALL",
    },
    "Day_Deep": {
        "name": "Day Deep Clouds",
        "satellite": "himawari",
        "bands": ["B08", "B13", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B13", "min": -35, "max": 5, "gamma": 1.0},
            "G": {"band": "B03", "min": 70, "max": 100, "gamma": 2},
            "B": {"band": "B13", "min": 243.6, "max": 292.6, "gamma": 1.0},
        },
        "description": "Ice-top storms cyan; warm-top storms yellow.",
        "tag": "DAY",
    },
    "dif_wat": {
        "name": "Differential Water Vapor",
        "satellite": "himawari",
        "bands": ["B10", "B08"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B10", "band2": "B08", "min": -3.0, "max": 30.0, "gamma": 0.7, "invert": True},
            "G": {"band": "B10", "min": 213.2, "max": 278.2, "gamma": 0.7, "invert": True},
            "B": {"band": "B08", "min": 208.5, "max": 243.9, "gamma": 0.7, "invert": True},
        },
        "description": "Fog yellow; clear dark; high cloud red.",
        "tag": "ALL",
    },
    "day_snowfog": {
        "name": "Day Snow-Fog",
        "satellite": "himawari",
        "bands": ["B04", "B06", "B07"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B04", "min": 0, "max": 121.4829, "gamma": 1},
            "G": {"band": "B06", "min": 0, "max": 90.1865, "gamma": 1},
            "B": {"band": "B07", "min": 196.5965, "max": 352.6322, "gamma": 1},
        },
        "description": "Fog detection in daytime (reflectance differences).",
        "tag": "DAY",
    },
    "basic_goes_true_color": {
        "name": "GOES True Color",
        "satellite": "goes",
        "bands": ["B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "G": {"operation": "weighted_sum", "bands": ["B03", "B02", "B01"], "weights": [0.45, 0.10, 0.45], "min": 0.0, "max": 100.0, "gamma": 3.0},
            "B": {"band": "B01", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "True color with synthetic green (CIMSS). (reflectance %)",
        "tag": "DAY",
    },
    "basic_goes_natural": {
        "name": "GOES Natural Color",
        "satellite": "goes",
        "bands": ["B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "G": {"band": "B02", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "B": {"band": "B01", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "Rayleigh-corrected true color. (reflectance %)",
        "tag": "DAY",
    },
    # ── GOES Standard RGB Products (adapted from Himawari AHI bands) ──
    "basic_goes_natural_swir": {
        "name": "Natural Color (SWIR)",
        "satellite": "goes",
        "bands": ["B05", "B02", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B05", "min": 0.0, "max": 99.0, "gamma": 3.0},
            "G": {"band": "B02", "min": 0.0, "max": 100.0, "gamma": 2.95},
            "B": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "Snow/ice cyan, vegetation green, clouds white (reflectance %). GOES B02 (C03/0.86µm) substitutes for Himawari B04.",
        "tag": "DAY",
    },
    "basic_goes_sandwich": {
        "name": "Sandwich",
        "satellite": "goes",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "sandwich",
        "description": "VIS underlaid with IR; cold clouds red/orange. Auto day/night switching via SZA.",
        "tag": "ALL",
    },
    "basic_goes_true_daynight": {
        "name": "GOES True Color Day/Night",
        "satellite": "goes",
        "bands": ["B13", "B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "special": "true_daynight",
        "description": "True Color by day with synthetic green (CIMSS), IR night background with cold cloud overlay. Auto day/night switching via SZA.",
        "tag": "ALL",
    },
    "basic_goes_geonatural_daynight": {
        "name": "GeoNatural Color Day/Night (PWARDS)",
        "satellite": "goes",
        "bands": ["B13", "B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "special": "true_daynight",
        "description": "True Color by day, IR night background with cold cloud overlay. Auto day/night switching via SZA.",
        "tag": "ALL",
    },
    "basic_goes_airmass": {
        "name": "Air Mass",
        "satellite": "goes",
        "bands": ["B08", "B10", "B12", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B10", "min": -25.8, "max": 0, "gamma": 1.0},
            "G": {"band1": "B12", "band2": "B13", "min": -41.5, "max": 4.3, "gamma": 1.0},
            "B": {"band": "B08", "min": 208.0, "max": 242.6, "gamma": 1.0, "invert": True},
        },
        "description": "Jet streams, tropopause folds, WV.",
        "tag": "ALL",
    },
    "basic_goes_dust": {
        "name": "Dust RGB",
        "satellite": "goes",
        "bands": ["B15", "B13", "B14", "B11"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3, "gamma": 1.0},
            "G": {"band1": "B14", "band2": "B11", "min": -0.5, "max": 15.0, "gamma": 2.2},
            "B": {"band": "B13", "min": 261.5, "max": 289.2, "gamma": 1.0},
        },
        "description": "Dust magenta/pink; thin cirrus dark; thick clouds brown.",
        "tag": "ALL",
    },
    "basic_goes_day_convection": {
        "name": "Day Convection",
        "satellite": "goes",
        "bands": ["B05", "B03", "B07", "B08", "B10", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B10", "min": -35.0, "max": 5.0, "gamma": 1.0},
            "G": {"band1": "B07", "band2": "B13", "min": -5.0, "max": 60.0, "gamma": 0.5},
            "B": {"band1": "B03", "band2": "B05", "min": -10.0, "max": 70.0, "gamma": 0.95, "invert": True},
        },
        "description": "Intense convection yellow; small ice crystals bright.",
        "tag": "DAY",
    },
    "basic_goes_fire": {
        "name": "Fire Temp",
        "satellite": "goes",
        "bands": ["B07", "B06", "B05"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B07", "min": 273.0, "max": 350.0, "gamma": 1.0},
            "G": {"band": "B06", "min": 0.0, "max": 50.0, "gamma": 1.0},
            "B": {"band": "B05", "min": 0.0, "max": 50.0, "gamma": 1.0},
        },
        "description": "Hot spots red/yellow; burn scars dark.",
        "tag": "DAY",
    },
    "basic_goes_night_microphysics": {
        "name": "Night Microphys.",
        "satellite": "goes",
        "bands": ["B10", "B13", "B15", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3, "gamma": 1},
            "G": {"band1": "B03", "band2": "B10", "min": -2.9, "max": 7, "gamma": 1},
            "B": {"band": "B13", "min": 243.7, "max": 293.2, "gamma": 1},
        },
        "description": "Fog/low clouds aqua; high ice clouds red/purple.",
        "tag": "NIGHT",
    },
    "basic_goes_cloud_phase": {
        "name": "Cloud Phase",
        "satellite": "goes",
        "bands": ["B05", "B06", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B05", "min": 1, "max": 50, "gamma": 1.0},
            "G": {"band": "B06", "min": 1, "max": 86, "gamma": 1.0},
            "B": {"band": "B01", "min": 0, "max": 86, "gamma": 1.0},
        },
        "description": "Ice clouds blue/cyan; liquid water white/green (reflectance %). GOES B01 (C01/0.47µm) substitutes for Himawari B02 (0.51µm green).",
        "tag": "DAY",
    },
    "basic_goes_infrared": {
        "name": "Infrared",
        "satellite": "goes",
        "bands": ["B13"],
        "single_band": True,
        "formula": {"band": "B13", "min": None, "max": None, "gamma": 0.5, "invert": True},
        "description": "Cold clouds white; warm ground black.",
        "tag": "ALL",
    },
    "basic_goes_day_microphysics": {
        "name": "Day Microphys.",
        "satellite": "goes",
        "bands": ["B07", "B02", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B02", "min": 0, "max": 121.4829, "gamma": 0.95},
            "G": {"band": "B07", "min": 196.5965, "max": 352.6322, "gamma": 1},
            "B": {"band": "B13", "min": 203.5, "max": 303.2, "gamma": 1.0},
        },
        "description": "Ice vs water cloud discrimination. GOES B02 (C03/0.86µm) substitutes for Himawari B04.",
        "tag": "DAY",
    },
    "basic_goes_volcanic_ash": {
        "name": "Ash RGB",
        "satellite": "goes",
        "bands": ["B11", "B13", "B14", "B15"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3.0, "gamma": 1.0},
            "G": {"band1": "B14", "band2": "B11", "min": -5.9, "max": 5.1, "gamma": 0.5},
            "B": {"band": "B13", "min": 243.6, "max": 303.2, "gamma": 1.0},
        },
        "description": "Ash cloud detection and tracking.",
        "tag": "ALL",
    },
    "basic_goes_day_deep": {
        "name": "Day Deep Clouds",
        "satellite": "goes",
        "bands": ["B08", "B13", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B13", "min": -35, "max": 5, "gamma": 1.0},
            "G": {"band": "B03", "min": 70, "max": 100, "gamma": 2},
            "B": {"band": "B13", "min": 243.6, "max": 292.6, "gamma": 1.0},
        },
        "description": "Ice-top storms cyan; warm-top storms yellow.",
        "tag": "DAY",
    },
    "basic_goes_differential_wv": {
        "name": "Differential Water Vapor",
        "satellite": "goes",
        "bands": ["B10", "B08"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B10", "band2": "B08", "min": -3.0, "max": 30.0, "gamma": 0.7, "invert": True},
            "G": {"band": "B10", "min": 213.2, "max": 278.2, "gamma": 0.7, "invert": True},
            "B": {"band": "B08", "min": 208.5, "max": 243.9, "gamma": 0.7, "invert": True},
        },
        "description": "Fog yellow; clear dark; high cloud red.",
        "tag": "ALL",
    },
    "basic_goes_day_snowfog": {
        "name": "Day Snow-Fog",
        "satellite": "goes",
        "bands": ["B02", "B06", "B07"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B02", "min": 0, "max": 121.4829, "gamma": 1},
            "G": {"band": "B06", "min": 0, "max": 90.1865, "gamma": 1},
            "B": {"band": "B07", "min": 196.5965, "max": 352.6322, "gamma": 1},
        },
        "description": "Fog detection in daytime (reflectance differences). GOES B02 (C03/0.86µm) substitutes for Himawari B04.",
        "tag": "DAY",
    },
    "gk2a_true": {
        "name": "GK-2A True Color",
        "satellite": "gk2a",
        "bands": ["B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "G": {"band": "B02", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "B": {"band": "B01", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "True color RGB for GK-2A AMI (reflectance %).",
        "tag": "DAY",
    },
    "gk2a_natural": {
        "name": "GK-2A Natural Color",
        "satellite": "gk2a",
        "bands": ["B05", "B04", "B03"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B05", "min": 0.0, "max": 99.0, "gamma": 3.0},
            "G": {"band": "B04", "min": 0.0, "max": 100.0, "gamma": 2.95},
            "B": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "Natural color for GK-2A (snow/ice cyan, vegetation green).",
        "tag": "DAY",
    },
    "gk2a_infrared": {
        "name": "GK-2A Infrared",
        "satellite": "gk2a",
        "bands": ["B13"],
        "single_band": True,
        "formula": {"band": "B13", "min": None, "max": None, "gamma": 0.5, "invert": True},
        "description": "IR brightness temperature for GK-2A.",
        "tag": "ALL",
    },
    "gk2a_airmass": {
        "name": "GK-2A Air Mass",
        "satellite": "gk2a",
        "bands": ["B08", "B10", "B12", "B13"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B08", "band2": "B10", "min": -25.8, "max": 0, "gamma": 1.0},
            "G": {"band1": "B12", "band2": "B13", "min": -41.5, "max": 4.3, "gamma": 1.0},
            "B": {"band": "B08", "min": 208.0, "max": 242.6, "gamma": 1.0, "invert": True},
        },
        "description": "Jet streams, tropopause folds, WV for GK-2A.",
        "tag": "ALL",
    },
    "gk2a_sandwich": {
        "name": "GK-2A Sandwich",
        "satellite": "gk2a",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "sandwich",
        "description": "VIS underlaid with IR; cold clouds red/orange for GK-2A.",
        "tag": "ALL",
    },
    "gk2a_true_daynight": {
        "name": "GK-2A True Color Day/Night",
        "satellite": "gk2a",
        "bands": ["B13", "B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "special": "true_daynight",
        "description": "True Color by day, IR night background with cold cloud overlay for GK-2A.",
        "tag": "ALL",
    },
    "gk2a_dust": {
        "name": "GK-2A Dust RGB",
        "satellite": "gk2a",
        "bands": ["B15", "B13", "B14", "B11"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B15", "band2": "B13", "min": -7.5, "max": 3, "gamma": 1.0},
            "G": {"band1": "B14", "band2": "B11", "min": -0.5, "max": 15.0, "gamma": 2.2},
            "B": {"band": "B13", "min": 261.5, "max": 289.2, "gamma": 1.0},
        },
        "description": "Dust magenta/pink for GK-2A.",
        "tag": "ALL",
    },
    "ms_airmass": {
        "name": "Meteosat Air Mass",
        "satellite": "meteosat",
        "bands": ["B07", "B09", "B10", "B11"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B07", "band2": "B09", "min": -25.8, "max": 0, "gamma": 1.0},
            "G": {"band1": "B10", "band2": "B11", "min": -41.5, "max": 4.3, "gamma": 1.0},
            "B": {"band": "B07", "min": 208.0, "max": 242.6, "gamma": 1.0, "invert": True},
        },
        "description": "Jet streams and air mass analysis for Meteosat SEVIRI.",
        "tag": "ALL",
    },
    "ms_infrared": {
        "name": "Meteosat Infrared",
        "satellite": "meteosat",
        "bands": ["B09"],
        "single_band": True,
        "formula": {"band": "B09", "min": None, "max": None, "gamma": 0.5, "invert": True},
        "description": "IR 10.8um brightness temperature for Meteosat.",
        "tag": "ALL",
    },
    "ms_natural": {
        "name": "Meteosat Natural Color",
        "satellite": "meteosat",
        "bands": ["B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band": "B03", "min": 0.0, "max": 100.0, "gamma": 3.0},
            "G": {"band": "B02", "min": 0.0, "max": 100.0, "gamma": 2.95},
            "B": {"band": "B01", "min": 0.0, "max": 100.0, "gamma": 3.0},
        },
        "description": "Natural color for Meteosat SEVIRI.",
        "tag": "DAY",
    },
    "ms_dust": {
        "name": "Meteosat Dust RGB",
        "satellite": "meteosat",
        "bands": ["B11", "B09", "B10", "B08"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B11", "band2": "B09", "min": -7.5, "max": 3, "gamma": 1.0},
            "G": {"band1": "B10", "band2": "B08", "min": -0.5, "max": 15.0, "gamma": 2.2},
            "B": {"band": "B09", "min": 261.5, "max": 289.2, "gamma": 1.0},
        },
        "description": "Dust detection for Meteosat SEVIRI.",
        "tag": "ALL",
    },
    "ms_night_microphysics": {
        "name": "Meteosat Night Microphys.",
        "satellite": "meteosat",
        "bands": ["B07", "B09", "B11", "B01"],
        "channels": ["R", "G", "B"],
        "formula": {
            "R": {"band1": "B11", "band2": "B09", "min": -7.5, "max": 3, "gamma": 1},
            "G": {"band1": "B01", "band2": "B07", "min": -2.9, "max": 7, "gamma": 1},
            "B": {"band": "B09", "min": 243.7, "max": 293.2, "gamma": 1},
        },
        "description": "Fog/low clouds detection for Meteosat.",
        "tag": "NIGHT",
    },
    # ── Color Scale / Professional Products ──
    "pro_dvorak": {
        "name": "Dvorak Enhancement",
        "satellite": "himawari",
        "color_scale": {"colormap": "Dvorak (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Dvorak TC intensity enhancement via color scale.",
        "tag": "PROFESSIONAL",
    },
    "pro_dvorak_experimental": {
        "name": "Dvorak Experimental (Node)",
        "satellite": "himawari",
        "color_scale": {"colormap": "Dvorak Experimental", "mode": "bt", "gamma": 1.0, "vmin": 173.15, "vmax": 323.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental Dvorak TC intensity enhancement via node-based color scale.",
        "tag": "PROFESSIONAL",
    },
    "pro_bt_enhanced": {
        "name": "BT Enhanced (IR)",
        "satellite": "himawari",
        "color_scale": {"colormap": "BT Enhanced (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Enhanced brightness temperature IR via color scale.",
        "tag": "PROFESSIONAL",
    },
    "pro_sandwich_ir": {
        "name": "Sandwich IR",
        "satellite": "himawari",
        "color_scale": {"colormap": "Sandwich (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Sandwich IR enhancement via color scale.",
        "tag": "PROFESSIONAL",
    },
    "pro_sandwich_ir_sataid": {
        "name": "Sandwich IR (SATAID)",
        "satellite": "himawari",
        "color_scale": {"colormap": "Sandwich IR (SATAID)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 343.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "SATAID Sandwich IR enhancement via Sandwich.dat 256-entry LUT (-73.15 to -33.15 C).",
        "tag": "PROFESSIONAL",
    },
    "pro_sandwich_sataid": {
        "name": "Sandwich (SATAID)",
        "satellite": "himawari",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "sandwich",
        "sataid_ir": True,
        "description": "SATAID Sandwich: VIS underlaid with IR; cold clouds via Sandwich.dat 256-entry LUT. Auto day/night switching via SZA.",
        "tag": "ALL",
    },
    "pro_jet": {
        "name": "Jet Colormap",
        "satellite": "himawari",
        "color_scale": {"colormap": "jet", "mode": "rad", "gamma": 1.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Jet colormap applied to the active band.",
        "tag": "PROFESSIONAL",
    },
    "pro_viridis": {
        "name": "Viridis Colormap",
        "satellite": "himawari",
        "color_scale": {"colormap": "viridis", "mode": "rad", "gamma": 1.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Viridis colormap applied to the active band.",
        "tag": "PROFESSIONAL",
    },
    "pro_inferno": {
        "name": "Inferno Colormap",
        "satellite": "himawari",
        "color_scale": {"colormap": "inferno", "mode": "rad", "gamma": 1.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Inferno colormap applied to the active band.",
        "tag": "PROFESSIONAL",
    },
    # GOES color scale products
    "basic_goes_pro_dvorak": {
        "name": "Dvorak Enhancement",
        "satellite": "goes",
        "color_scale": {"colormap": "Dvorak (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Dvorak TC intensity enhancement via color scale (GOES).",
        "tag": "PROFESSIONAL",
    },
    "basic_goes_pro_dvorak_experimental": {
        "name": "Dvorak Experimental (Node)",
        "satellite": "goes",
        "color_scale": {"colormap": "Dvorak Experimental", "mode": "bt", "gamma": 1.0, "vmin": 173.15, "vmax": 323.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental Dvorak TC intensity enhancement via node-based color scale (GOES).",
        "tag": "PROFESSIONAL",
    },
    "basic_goes_pro_bt_enhanced": {
        "name": "BT Enhanced (IR)",
        "satellite": "goes",
        "color_scale": {"colormap": "BT Enhanced (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Enhanced brightness temperature IR via color scale (GOES).",
        "tag": "PROFESSIONAL",
    },
    "basic_goes_pro_jet": {
        "name": "Jet Colormap",
        "satellite": "goes",
        "color_scale": {"colormap": "jet", "mode": "rad", "gamma": 1.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Jet colormap applied to the active band (GOES).",
        "tag": "PROFESSIONAL",
    },
    # GK-2A color scale products
    "gk2a_pro_dvorak": {
        "name": "Dvorak Enhancement",
        "satellite": "gk2a",
        "color_scale": {"colormap": "Dvorak (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Dvorak TC intensity enhancement via color scale (GK-2A).",
        "tag": "PROFESSIONAL",
    },
    "gk2a_pro_dvorak_experimental": {
        "name": "Dvorak Experimental (Node)",
        "satellite": "gk2a",
        "color_scale": {"colormap": "Dvorak Experimental", "mode": "bt", "gamma": 1.0, "vmin": 173.15, "vmax": 323.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental Dvorak TC intensity enhancement via node-based color scale (GK-2A).",
        "tag": "PROFESSIONAL",
    },
    "gk2a_pro_bt_enhanced": {
        "name": "BT Enhanced (IR)",
        "satellite": "gk2a",
        "color_scale": {"colormap": "BT Enhanced (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Enhanced brightness temperature IR via color scale (GK-2A).",
        "tag": "PROFESSIONAL",
    },
    "gk2a_pro_jet": {
        "name": "Jet Colormap",
        "satellite": "gk2a",
        "color_scale": {"colormap": "jet", "mode": "rad", "gamma": 1.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Jet colormap applied to the active band (GK-2A).",
        "tag": "PROFESSIONAL",
    },
    # Meteosat color scale products
    "ms_pro_dvorak": {
        "name": "Dvorak Enhancement",
        "satellite": "meteosat",
        "color_scale": {"colormap": "Dvorak (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Dvorak TC intensity enhancement via color scale (Meteosat).",
        "tag": "PROFESSIONAL",
    },
    "ms_pro_dvorak_experimental": {
        "name": "Dvorak Experimental (Node)",
        "satellite": "meteosat",
        "color_scale": {"colormap": "Dvorak Experimental", "mode": "bt", "gamma": 1.0, "vmin": 173.15, "vmax": 323.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental Dvorak TC intensity enhancement via node-based color scale (Meteosat).",
        "tag": "PROFESSIONAL",
    },
    "ms_pro_bt_enhanced": {
        "name": "BT Enhanced (IR)",
        "satellite": "meteosat",
        "color_scale": {"colormap": "BT Enhanced (IR)", "mode": "bt", "gamma": 1.0, "vmin": 173.0, "vmax": 323.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Enhanced brightness temperature IR via color scale (Meteosat).",
        "tag": "PROFESSIONAL",
    },
    "ms_pro_jet": {
        "name": "Jet Colormap",
        "satellite": "meteosat",
        "color_scale": {"colormap": "jet", "mode": "rad", "gamma": 1.0},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Jet colormap applied to the active band (Meteosat).",
        "tag": "PROFESSIONAL",
    },
    # Experimental SST (IR) products
    "pro_experimental_sst": {
        "name": "Experimental SST (IR)",
        "satellite": "himawari",
        "color_scale": {"colormap": "SST (IR)", "mode": "bt", "gamma": 1.0, "vmin": 273.15, "vmax": 313.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental sea surface temperature from IR bands. Yellow-red overlay for 0-40°C.",
        "tag": "PROFESSIONAL",
    },
    "basic_goes_pro_experimental_sst": {
        "name": "Experimental SST (IR)",
        "satellite": "goes",
        "color_scale": {"colormap": "SST (IR)", "mode": "bt", "gamma": 1.0, "vmin": 273.15, "vmax": 313.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental sea surface temperature from IR bands. Yellow-red overlay for 0-40°C (GOES).",
        "tag": "PROFESSIONAL",
    },
    "gk2a_pro_experimental_sst": {
        "name": "Experimental SST (IR)",
        "satellite": "gk2a",
        "color_scale": {"colormap": "SST (IR)", "mode": "bt", "gamma": 1.0, "vmin": 273.15, "vmax": 313.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental sea surface temperature from IR bands. Yellow-red overlay for 0-40°C (GK-2A).",
        "tag": "PROFESSIONAL",
    },
    "ms_pro_experimental_sst": {
        "name": "Experimental SST (IR)",
        "satellite": "meteosat",
        "color_scale": {"colormap": "SST (IR)", "mode": "bt", "gamma": 1.0, "vmin": 273.15, "vmax": 313.15},
        "bands": [],
        "channels": ["R", "G", "B"],
        "description": "Experimental sea surface temperature from IR bands. Yellow-red overlay for 0-40°C (Meteosat).",
        "tag": "PROFESSIONAL",
    },
    # ── False Color RGB Products ──
    "false_color": {
        "name": "False Color RGB",
        "satellite": "himawari",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "false_color",
        "description": "VIS/IR false color composite with SZA normalization. Vegetation green, convective clouds pink.",
        "tag": "ALL",
    },
    "goes_false_color": {
        "name": "GOES False Color RGB",
        "satellite": "goes",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "false_color",
        "description": "VIS/IR false color composite with SZA normalization. Vegetation green, convective clouds pink.",
        "tag": "ALL",
    },
    "gk2a_false_color": {
        "name": "GK-2A False Color RGB",
        "satellite": "gk2a",
        "bands": ["B13", "B03"],
        "channels": ["R", "G", "B"],
        "special": "false_color",
        "description": "VIS/IR false color composite with SZA normalization for GK-2A AMI.",
        "tag": "ALL",
    },
    "ms_false_color": {
        "name": "Meteosat False Color RGB",
        "satellite": "meteosat",
        "bands": ["B09", "B01"],
        "channels": ["R", "G", "B"],
        "special": "false_color",
        "description": "VIS/IR false color composite with SZA normalization for Meteosat SEVIRI (VIS006 + IR108).",
        "tag": "ALL",
    },
    # ── Unidata True Color Recipes (day + day/night; see core/unidata_truecolor.py) ──
    "true_color_unidata": {
        "name": "True Color (Unidata)",
        "satellite": "himawari",
        "bands": ["B03", "B04", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B03",
        "g_band": "B04",
        "b_band": "B01",
        "ir_band": None,
        "special": "true_color_unidata",
        "natural": False,
        "contrast": 105,
        "description": "Unidata True Color Recipe: clip, gamma 2.2, CIMSS synthetic green. Himawari R=B03(0.64), G=B04(0.86), B=B01(0.47) reflectance. (day)",
        "tag": "DAY",
    },
    "true_daynight_unidata": {
        "name": "True Color Day/Night (Unidata)",
        "satellite": "himawari",
        "bands": ["B13", "B03", "B04", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B03",
        "g_band": "B04",
        "b_band": "B01",
        "ir_band": "B13",
        "special": "true_color_unidata",
        "natural": False,
        "contrast": 105,
        "description": "Unidata True Color by day with clean IR (B13) night cloud overlay. Auto day/night blend via solar zenith angle.",
        "tag": "ALL",
    },
    "goes_true_color_unidata": {
        "name": "True Color (Unidata)",
        "satellite": "goes",
        "bands": ["B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B02",
        "g_band": "B03",
        "b_band": "B01",
        "ir_band": None,
        "special": "true_color_unidata",
        "natural": False,
        "contrast": 105,
        "description": "Unidata True Color Recipe: clip, gamma 2.2, CIMSS synthetic green. GOES R=C02(0.64), G=C03(0.86), B=C01(0.47) reflectance. (day)",
        "tag": "DAY",
    },
    "goes_true_daynight_unidata": {
        "name": "True Color Day/Night (Unidata)",
        "satellite": "goes",
        "bands": ["B13", "B03", "B02", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B02",
        "g_band": "B03",
        "b_band": "B01",
        "ir_band": "B13",
        "special": "true_color_unidata",
        "natural": False,
        "contrast": 105,
        "description": "Unidata True Color by day with clean IR (C13) night cloud overlay. Auto day/night blend via solar zenith angle.",
        "tag": "ALL",
    },
    "gk2a_true_color_unidata": {
        "name": "True Color (Unidata)",
        "satellite": "gk2a",
        "bands": ["B03", "B04", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B03",
        "g_band": "B04",
        "b_band": "B01",
        "ir_band": None,
        "special": "true_color_unidata",
        "natural": False,
        "contrast": 105,
        "description": "Unidata True Color Recipe: clip, gamma 2.2, CIMSS synthetic green. GK-2A R=B03(0.64), G=B04(0.86), B=B01(0.47) reflectance. (day)",
        "tag": "DAY",
    },
    "gk2a_true_daynight_unidata": {
        "name": "True Color Day/Night (Unidata)",
        "satellite": "gk2a",
        "bands": ["B13", "B03", "B04", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B03",
        "g_band": "B04",
        "b_band": "B01",
        "ir_band": "B13",
        "special": "true_color_unidata",
        "natural": False,
        "contrast": 105,
        "description": "Unidata True Color by day with clean IR (B13) night cloud overlay for GK-2A AMI. Auto day/night blend via solar zenith angle.",
        "tag": "ALL",
    },
    "ms_true_color_unidata": {
        "name": "True Color (Natural) (Unidata)",
        "satellite": "meteosat",
        "bands": ["B02", "B03", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B02",
        "g_band": "B03",
        "b_band": "B01",
        "ir_band": None,
        "special": "true_color_unidata",
        "natural": True,
        "contrast": 105,
        "description": "Unidata-style True Color for Meteosat SEVIRI (no native blue/green: natural-color substitute R=VIS008, G=IR016, B=VIS006). Clip, gamma 2.2. (day)",
        "tag": "DAY",
    },
    "ms_true_daynight_unidata": {
        "name": "True Color Day/Night (Natural) (Unidata)",
        "satellite": "meteosat",
        "bands": ["B09", "B02", "B03", "B01"],
        "channels": ["R", "G", "B"],
        "r_band": "B02",
        "g_band": "B03",
        "b_band": "B01",
        "ir_band": "B09",
        "special": "true_color_unidata",
        "natural": True,
        "contrast": 105,
        "description": "Unidata-style True Color by day with clean IR (B09/IR108) night cloud overlay for Meteosat SEVIRI. Auto day/night blend via solar zenith angle.",
        "tag": "ALL",
    },
}


def get_products_for_satellite(sat: str) -> dict:
    """Return RGB_PRODUCTS entries matching the given satellite family."""
    s = sat.lower()
    if "goes" in s:
        target = "goes"
    elif "gk2a" in s or "gk-2a" in s:
        target = "gk2a"
    elif "meteosat" in s or "msg" in s:
        target = "meteosat"
    else:
        target = "himawari"
    return {k: v for k, v in RGB_PRODUCTS.items()
            if v.get("satellite") == target}


_TAG_COLORS = {"DAY": "#E65100", "NIGHT": "#1A237E", "ALL": "#1B5E20", "PROFESSIONAL": "#6A1B9A"}
